'use client';

import { useCallback, useEffect, useState } from 'react';
import { AlertTriangle, Boxes, Download, HandCoins, Landmark, ReceiptText, ShoppingCart, TrendingUp } from 'lucide-react';
import { useRouter } from 'next/navigation';
import Header from '@/components/Header';
import { useAuth } from '@/lib/AuthContext';
import { supabase } from '@/lib/supabaseClient';
import type { MonthlyAnalytics } from '@/lib/types';

const money=(value:number)=>new Intl.NumberFormat('en-ET',{style:'currency',currency:'ETB',maximumFractionDigits:0}).format(value);
export default function AnalyticsPage(){
  const {profile,session}=useAuth();const router=useRouter();const [data,setData]=useState<MonthlyAnalytics|null>(null);const [error,setError]=useState<string|null>(null);const [exporting,setExporting]=useState(false);const allowed=profile?.role==='SUPER_ADMIN'||(profile?.role==='ADMIN'&&profile.analytics_access);
  const load=useCallback(async()=>{const {data:rows,error:e}=await supabase.rpc('get_monthly_analytics',{month_start:new Date(new Date().getFullYear(),new Date().getMonth(),1).toISOString().slice(0,10)});if(e)setError(e.message);else setData(((rows as MonthlyAnalytics[])??[])[0]??null)},[]);
  useEffect(()=>{if(!allowed)router.replace(profile?.role==='BASIC'?'/outlets':'/');else void load()},[allowed,load,profile?.role,router]);
  const download=async()=>{if(!session)return;setExporting(true);setError(null);const response=await fetch('/api/admin/export',{headers:{Authorization:`Bearer ${session.access_token}`}});if(!response.ok){const body=await response.json() as {error?:string};setError(body.error??'Export failed.');setExporting(false);return;}const blob=await response.blob();const url=URL.createObjectURL(blob);const anchor=document.createElement('a');anchor.href=url;anchor.download=response.headers.get('content-disposition')?.match(/filename="([^"]+)"/)?.[1]??'KONJO-Accounting-Export.xlsx';anchor.click();URL.revokeObjectURL(url);setExporting(false)};
  if(!allowed)return null;const cards=data?[['Total Current Inventory',data.total_current_inventory,Boxes,false],['Outlet Inventory',data.outlet_inventory,Boxes,false],['Sales Volume',data.total_sales_volume,ShoppingCart,false],['Pending Sales',data.pending_sales,ReceiptText,true],['Projected Sales',data.projected_sales,TrendingUp,true],['Gross Revenue',data.gross_revenue,HandCoins,true],['Net Revenue (Before Tax)',data.net_revenue,Landmark,true],['Tax Liability',data.total_tax_liability,ReceiptText,true]] as const:[];const max=Math.max(1,...cards.map(c=>Number(c[1])));
  return <div className="min-h-dvh bg-konjo-charcoal pb-10"><Header title="Accounting Analytics" subtitle="current month"/><main className="mx-auto max-w-6xl px-4 pt-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-[10px] font-bold uppercase tracking-[0.2em] text-konjo-red">Management view</p><h1 className="mt-1 font-display text-2xl font-bold text-konjo-cream">Monthly operating picture</h1></div>{profile?.role==='SUPER_ADMIN'&&<button onClick={()=>void download()} disabled={exporting} className="flex h-12 items-center gap-2 rounded-xl bg-konjo-green px-4 text-xs font-bold text-white shadow-lg shadow-konjo-green/20 disabled:opacity-50"><Download size={17}/>{exporting?'Building workbook…':'Export to Spreadsheet'}</button>}</div>{error&&<p className="mt-4 rounded-xl bg-konjo-red/10 p-3 text-xs text-konjo-red">{error}</p>}
    <div className="mt-5 grid grid-cols-2 gap-3 lg:grid-cols-4">{cards.map(([label,value,Icon,isMoney])=><article key={label} className="rounded-2xl border border-white/10 bg-white/[0.045] p-4"><Icon size={17} className="text-konjo-amber"/><p className="mt-3 font-display text-xl font-bold tabular-nums text-konjo-cream">{isMoney?money(Number(value)):Number(value).toLocaleString()}</p><p className="mt-1 text-[10px] text-konjo-cream/40">{label}</p><div className="mt-3 h-1.5 overflow-hidden rounded-full bg-white/5"><div className="h-full rounded-full bg-gradient-to-r from-konjo-red to-konjo-amber" style={{width:`${Math.max(3,Number(value)/max*100)}%`}}/></div></article>)}</div>
    {data&&<div className="mt-4 grid gap-3 sm:grid-cols-4"><div className="rounded-2xl border border-white/10 bg-white/[0.035] p-4"><p className="font-display text-2xl font-bold text-konjo-cream">{data.outstanding_orders}</p><p className="text-[10px] text-konjo-cream/35">Outstanding orders</p></div><div className="rounded-2xl border border-white/10 bg-white/[0.035] p-4"><p className="font-display text-2xl font-bold text-konjo-cream">{data.active_outlets}</p><p className="text-[10px] text-konjo-cream/35">Active outlets</p></div><div className="rounded-2xl border border-konjo-amber/20 bg-konjo-amber/[0.06] p-4"><AlertTriangle className="text-konjo-amber" size={16}/><p className="mt-2 font-display text-2xl font-bold text-konjo-cream">{data.low_stock_products}</p><p className="text-[10px] text-konjo-cream/35">Low-stock products</p></div><div className="rounded-2xl border border-white/10 bg-white/[0.035] p-4"><p className="font-display text-2xl font-bold text-konjo-cream">{(Number(data.inventory_turnover)*100).toFixed(1)}%</p><p className="text-[10px] text-konjo-cream/35">Monthly inventory turnover</p></div></div>}
  </main></div>;
}
