'use client';

import { useState } from 'react';
import { X } from 'lucide-react';
import type { Product } from '@/lib/types';

export default function ProductEditModal({product,onClose,onSave}:{product:Product;onClose:()=>void;onSave:(product:Product)=>Promise<boolean>}){
  const [draft,setDraft]=useState(product);const [saving,setSaving]=useState(false);const [error,setError]=useState<string|null>(null);
  const save=async()=>{if(!draft.name.trim()||!draft.sku.trim()||!draft.category.trim())return setError('Name, SKU and category are required.');setSaving(true);const ok=await onSave({...draft,name:draft.name.trim(),sku:draft.sku.trim().toUpperCase(),category:draft.category.trim()});setSaving(false);if(ok)onClose();else setError('Could not save product details.')};
  return <div className="fixed inset-0 z-50 flex items-end justify-center bg-black/70 sm:items-center" onClick={onClose}><div onClick={e=>e.stopPropagation()} className="w-full max-w-md rounded-t-3xl border border-white/10 bg-konjo-charcoal-2 p-5 sm:rounded-3xl"><div className="flex items-center justify-between"><div><h2 className="font-display text-lg font-bold text-konjo-cream">Edit Product Details</h2><p className="text-[10px] text-konjo-cream/35">Catalog metadata only; stock history is unchanged.</p></div><button onClick={onClose} className="rounded-full bg-white/5 p-2 text-konjo-cream/60"><X size={16}/></button></div>
    <div className="mt-5 space-y-3"><label className="block text-xs text-konjo-cream/50">Product name<input value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})} className="mt-1 w-full rounded-xl border border-white/10 bg-black/15 px-3 py-3 text-sm text-konjo-cream"/></label><div className="grid grid-cols-2 gap-3"><label className="block text-xs text-konjo-cream/50">SKU<input value={draft.sku} onChange={e=>setDraft({...draft,sku:e.target.value})} className="mt-1 w-full rounded-xl border border-white/10 bg-black/15 px-3 py-3 font-mono text-sm text-konjo-cream"/></label><label className="block text-xs text-konjo-cream/50">Category<input value={draft.category} onChange={e=>setDraft({...draft,category:e.target.value})} className="mt-1 w-full rounded-xl border border-white/10 bg-black/15 px-3 py-3 text-sm text-konjo-cream"/></label></div><label className="block text-xs text-konjo-cream/50">Low-stock threshold<input type="number" min="0" value={draft.low_stock_threshold} onChange={e=>setDraft({...draft,low_stock_threshold:Math.max(0,Number(e.target.value))})} className="mt-1 w-full rounded-xl border border-white/10 bg-black/15 px-3 py-3 text-sm text-konjo-cream"/></label><label className="block text-xs text-konjo-cream/50">Description<textarea rows={4} value={draft.description??''} onChange={e=>setDraft({...draft,description:e.target.value})} className="mt-1 w-full resize-none rounded-xl border border-white/10 bg-black/15 px-3 py-3 text-sm text-konjo-cream"/></label></div>{error&&<p className="mt-3 text-xs text-konjo-red">{error}</p>}<button onClick={()=>void save()} disabled={saving} className="mt-5 h-12 w-full rounded-xl bg-konjo-red font-bold text-white disabled:opacity-50">{saving?'Saving…':'Save product details'}</button>
  </div></div>;
}
