'use client';

import { useCallback, useEffect, useMemo, useState } from 'react';
import { BarChart3, KeyRound, Search, Shield, UserRound } from 'lucide-react';
import { useRouter } from 'next/navigation';
import Header from '@/components/Header';
import { useAuth } from '@/lib/AuthContext';
import { supabase } from '@/lib/supabaseClient';
import type { UserProfile, UserRole } from '@/lib/types';

export default function UserManagementPage() {
  const { profile, session } = useAuth(); const router = useRouter();
  const [users, setUsers] = useState<UserProfile[]>([]); const [query, setQuery] = useState('');
  const [message, setMessage] = useState<string | null>(null); const [working, setWorking] = useState<string | null>(null);
  const isRoot = profile?.role === 'SUPER_ADMIN' && profile.username.toLowerCase() === 'natanim';
  const load = useCallback(async () => { const { data, error } = await supabase.rpc('list_user_profiles'); if (error) setMessage(error.message); else setUsers((data as UserProfile[]) ?? []); }, []);
  useEffect(() => { if (!isRoot) router.replace('/'); else void load(); }, [isRoot, load, router]);
  const filtered = useMemo(() => users.filter(user => `${user.display_name} ${user.username}`.toLowerCase().includes(query.toLowerCase())), [query, users]);
  const basics = filtered.filter(user => user.role === 'BASIC'); const admins = filtered.filter(user => user.role === 'ADMIN');
  const setRole = async (user: UserProfile, role: Extract<UserRole, 'ADMIN' | 'BASIC'>) => { setWorking(user.id); setMessage(null); const { error } = await supabase.rpc('set_user_role', { target_user_id: user.id, new_role: role }); setWorking(null); if (error) setMessage(error.message); else void load(); };
  const setAnalytics = async (user: UserProfile, enabled: boolean) => { setWorking(user.id); const { error } = await supabase.rpc('set_analytics_access', { target_user_id: user.id, enabled }); setWorking(null); if (error) setMessage(error.message); else void load(); };
  const reset = async (user: UserProfile) => { if (!session) return; setWorking(user.id); setMessage(null); const response = await fetch(`/api/admin/users/${user.id}/temporary-password`, { method: 'POST', headers: { Authorization: `Bearer ${session.access_token}` } }); const body = await response.json() as { temporary_password?: string; error?: string }; setWorking(null); setMessage(response.ok ? `Temporary password for ${user.display_name}: ${body.temporary_password} — copy it now; it will not be shown again.` : body.error ?? 'Reset failed.'); if (response.ok) void load(); };
  const table = (title: string, rows: UserProfile[], adminTable = false) => <section className="rounded-2xl border border-white/10 bg-white/[0.035] p-4"><div className="flex items-center gap-2"><span className={`rounded-lg p-2 ${adminTable ? 'bg-konjo-amber/10 text-konjo-amber' : 'bg-white/5 text-konjo-cream/50'}`}>{adminTable ? <Shield size={16} /> : <UserRound size={16} />}</span><div><h2 className="font-display text-sm font-bold text-konjo-cream">{title}</h2><p className="text-[10px] text-konjo-cream/35">{rows.length} accounts</p></div></div><div className="mt-3 overflow-x-auto"><table className="w-full min-w-[640px] text-left"><thead><tr className="border-b border-white/10 text-[9px] uppercase tracking-wide text-konjo-cream/30"><th className="px-2 py-2">Employee</th><th className="px-2 py-2">Access</th><th className="px-2 py-2">Security</th><th className="px-2 py-2 text-right">Actions</th></tr></thead><tbody>{rows.map(user => <tr key={user.id} className="border-b border-white/5 text-xs"><td className="px-2 py-3"><p className="font-semibold text-konjo-cream">{user.display_name}</p><p className="text-[10px] text-konjo-cream/30">@{user.username}</p></td><td className="px-2 py-3 text-konjo-cream/50">{adminTable ? <button onClick={() => void setAnalytics(user, !user.analytics_access)} className={`flex items-center gap-1 rounded-lg px-2 py-1 ${user.analytics_access ? 'bg-konjo-green/15 text-konjo-green' : 'bg-white/5'}`}><BarChart3 size={12} />{user.analytics_access ? 'Analytics on' : 'Analytics off'}</button> : 'Field Sales'}</td><td className="px-2 py-3">{user.must_reset_password ? <span className="text-konjo-amber">Reset required</span> : <span className="text-konjo-green">Active</span>}</td><td className="px-2 py-3"><div className="flex justify-end gap-2"><button disabled={working === user.id} onClick={() => void reset(user)} className="flex items-center gap-1 rounded-lg border border-white/10 px-2 py-2 text-[10px] font-bold text-konjo-cream/60"><KeyRound size={12} />Temporary password</button><button disabled={working === user.id} onClick={() => void setRole(user, adminTable ? 'BASIC' : 'ADMIN')} className={`rounded-lg px-3 py-2 text-[10px] font-bold ${adminTable ? 'bg-white/10 text-konjo-cream/60' : 'bg-konjo-amber text-konjo-charcoal'}`}>{adminTable ? 'Demote' : 'Promote'}</button></div></td></tr>)}</tbody></table>{!rows.length && <p className="py-6 text-center text-xs text-konjo-cream/30">No matching employees.</p>}</div></section>;
  if (!isRoot) return null;
  return <div className="min-h-dvh bg-konjo-charcoal pb-10"><Header title="User Role Management" subtitle="Root Owner only" /><main className="mx-auto max-w-5xl px-4 pt-5"><div className="flex h-11 items-center gap-2 rounded-xl border border-white/10 bg-white/[0.04] px-3"><Search size={15} className="text-konjo-cream/35" /><input value={query} onChange={event => setQuery(event.target.value)} placeholder="Search employees by name" className="w-full bg-transparent text-sm text-konjo-cream outline-none" /></div>{message && <p className="mt-3 rounded-xl border border-konjo-amber/20 bg-konjo-amber/10 p-3 text-xs leading-relaxed text-konjo-cream">{message}</p>}<div className="mt-4 space-y-4">{table('Basic Employees', basics)}{table('Admins', admins, true)}</div></main></div>;
}
